version: '3'

volumes:
  pgdata:
  irods-data:

services:
  dns-proxy-server:
    image: defreitas/dns-proxy-server
    expose:
      - "5380"
    hostname: dns.mageddo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
  icat:
    build:
      context: .
      dockerfile: Dockerfile.server
    hostname: irods.icat
    expose:
      - "1247"
      - "1248"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - irods-data:/data

#  client:
#    build:
#      context: .
#      dockerfile: Dockerfile.client
#    hostname: irods.client
#    volumes:
#      - irods-config:/etc/irods
#      - irods-lib:/var/lib/irods
#      - irods-data:/data
